package ua.in.smartjava.domain;

import java.util.List;

import javax.persistence.Convert;
import javax.persistence.ElementCollection;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Hibernate: create table employee (
 *  id bigint generated by default as identity,
 *  name varchar(255),
 *  bonded integer,
 *  top_skilled integer,
 *  primary key (id))
 *
 *  Hibernate: create table employee_secured (employee_id bigint not null, secured integer)
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

    @Id
    @GeneratedValue
    private long id;

    private String name;

    // integer in DB Boolean in entity
    @Convert(converter = BooleanToIntegerConverter.class)
    private Boolean topSkilled;

    @Convert(converter = BooleanToIntegerConverter.class, attributeName = "bonded")
    private SecurityInfo securityInfo;

    @ElementCollection
    @Convert(converter = BooleanToIntegerConverter.class)
    private List<Boolean> secured;

}

@Embeddable
@AllArgsConstructor
@NoArgsConstructor
class SecurityInfo {
    private Boolean bonded;
}
